language: go

go:
    - "1.12.x"
before_install:
    - go get -u github.com/golang/dep/cmd/dep
    - npm install -g serverless
# script:
#     - sls deploy
install: true

script:
    - go test -v # Run all the tests
